---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-certs
  namespace: elastic-stack
spec:
  secretName: elasticsearch-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - elasticsearch-master.elastic-stack.svc.cluster.local
    - elasticsearch.localhost
  commonName: elasticsearch-master.elastic-stack.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-certs
  namespace: elastic-stack
spec:
  secretName: kibana-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - kibana.elastic-stack.svc.cluster.local
    - kibana.localhost
  commonName: kibana.elastic-stack.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fluentd-certs
  namespace: logging
spec:
  secretName: fluentd-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - fluentd.logging.svc.cluster.local
  commonName: fluentd.logging.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certs
  namespace: monitoring
spec:
  secretName: prometheus-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.monitoring.svc.cluster.local
    - prometheus.localhost
  commonName: prometheus.monitoring.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certs
  namespace: monitoring
spec:
  secretName: grafana-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.monitoring.svc.cluster.local
    - grafana.localhost
  commonName: prometheus.monitoring.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-certs
  namespace: observability
spec:
  secretName: jaeger-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - jaeger.observability.svc.cluster.local
    - jaeger.localhost
  commonName: jaeger.observability.svc.cluster.local