apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - jaeger.localhost
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master.elastic-stack.svc.cluster.local:9200
