apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
  namespace: observability
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    processors:
      batch:
    exporters:
      logging:
        loglevel: debug
        prometheus:
          endpoint: "0.0.0.0:8889"
          const_labels:
            labels: spring
        otlp:
          endpoint: tempo.observability.svc.cluster.local:4317
          tls:
            insecure: true
          elasticsearch:
            endpoint: "elasticsearch.logging.svc.cluster.local"
    extensions:
      health_check:
      pprof:
      zpages:
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]
