apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
  namespace: observability
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            # FIX 2: Use '0.0.0.0' to bind to all interfaces instead of relying on MY_POD_IP
            endpoint: "0.0.0.0:4317"
          http:
            # FIX 2: Use '0.0.0.0' to bind to all interfaces instead of relying on MY_POD_IP
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
          labels: spring
      otlp:
        endpoint: "tempo.observability.svc.cluster.local:4317"
        tls:
          insecure: true
      elasticsearch:
        endpoints: ["http://elasticsearch.logging.svc.cluster.local:9200"]
        logs_index: "app-logs" # Direct string value
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    service:
      extensions: [health_check] # Now this reference is valid
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch, debug]
