ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - pyroscope.localhost
  tls:
    - hosts:
      - pyroscope.localhost
      secretName: pyroscope-localhost-tls
