datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
      - name: Tempo
        type: tempo
        url: http://tempo.observability.svc.cluster.local:3200
        access: proxy
        jsonData:
          search:
            maxSearchDuration: 1m
            maxTraceDuration: 1h
      - name: Parca
        type: parca
        url: http://parca-parca.observability.svc.cluster.local:80
        access: proxy

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.localhost
  path: /

service:
  type: NodePort

persistence:
  enabled: false
