# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"
# ingress
ingress:
  enabled: true
  hosts:
    - host: elasticsearch.localhost
      paths:
        - path: /
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - elasticsearch.localhost
      secretName: elasticsearch-localhost-tls
# Adjust readiness probe
readinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 30
# Single-node deployment for Kind
replicas: 1
# Disable persistent storage (Kind doesn't support persistent volumes by default)
persistence:
  enabled: false
# Configure JVM heap size (adjust based on available resources)
esJavaOpts: "-Xms1536m -Xmx1536m"
# Minimal resource requests/limits for Kind
resources:
  requests:
    memory: "3Gi"
    cpu: "1"
  limits:
    memory: "3Gi"
    cpu: "2"
xpack:
  security:
    enabled: false
  monitoring:
    enabled: false
  watcher:
    enabled: false
  ml:
    enabled: false
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.monitoring.enabled: false
    xpack.watcher.enabled: false
    xpack.ml.enabled: false
    xpack.security.http.ssl.enabled: false
extraEnvs:
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"
# Expose the service via a NodePort for local access
service:
  type: NodePort
# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 100M
