# values.yaml
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib # This is correct now
  autoInstrumentationImage:
    java:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
      tag: 1.33.6

admissionWebhooks:
  certManager:
    issuerRef:
      kind: ClusterIssuer
      name: selfsigned-cluster-issuer
