# Connect Kibana to Elasticsearch
elasticsearchHosts: "http://elasticsearch-master:9200"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: kibana.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - kibana.localhost
      secretName: kibana-localhost-tls
# Minimal resource requests/limits for Kind
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2"
# Expose the service via a NodePort for local access
service:
  type: NodePort
kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "https://kibana.localhost"
