config:
  otel:
    collectors:
      otlp:
        protocol: http
        host: 0.0.0.0
        port: 4317
      prometheus:
        protocol: http
        host: 0.0.0.0
        port: 8889
    exporters:
      prometheus:
        endpoint: http://prometheus-server.monitoring.svc.cluster.local:9090
      jaeger:
        endpoint: http://jaeger-collector.observability.svc.cluster.local:14268/api/traces
      tempo:
        endpoint: http://tempo-tempo.observability.svc.cluster.local:3200
      parca:
        endpoint: http://parca-parca.observability.svc.cluster.local:80
      logging:
        loglevel: debug

service:
  type: ClusterIP
  port: 4317

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2"
