service:
  enabled: true
  name: config-server
  port: 8888
  type: ClusterIP

deployment:
  replicaCount: 1
  image: springcommunity/spring-petclinic-microservices-config-server:latest
  imagePullPolicy: IfNotPresent
  javaOpts: ""
  logLevel: "INFO"
  env:
    SPRING_PROFILES_ACTIVE: "kubernetes,native,git"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

probes:
  liveness:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 10
  readiness:
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 5
  startup:
    path: /actuator/health
    failureThreshold: 20
    periodSeconds: 10
