# Default values that can be overridden by each service
service:
  enabled: true
  name: ""
  port: 8080
  type: ClusterIP
  annotations: {}

deployment:
  replicaCount: 1
  image: ""
  imagePullPolicy: IfNotPresent
  javaOpts: ""
  logLevel: "INFO"

  env:
    SPRING_PROFILES_ACTIVE: "kubernetes"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
    SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  startup:
    path: /actuator/health/readiness
    failureThreshold: 30
    periodSeconds: 10
